diary/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),#网站首页
    path('category-<int:cid>.html', views.category, name='category'),#目录
    path('archive/<int:year>/<int:month>', views.archive, name='archive'),#归档页面
    path('search/', views.search, name='search'),#搜索列表页
    path('show-<int:sid>.html', views.show, name='show'),#内容页
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('diary.urls','diary'),namespace='diary')),
    path('mdeditor/', include('mdeditor.urls')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diary/models.py
from django.db import models
from mdeditor.fields import MDTextField
from datetime import date

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name



class ArticleManager(models.Manager):
    def archive(self):
        archive_list = []
        date_list = self.values('date')
        for date in date_list:
            date = date['date'].strftime('%Y年%m月')
            if date not in archive_list:
                archive_list.append(date)
        return archive_list

class Article(models.Model):
    title = models.CharField(max_length=50,blank=True)
    excerpt = models.TextField(max_length=200, blank=True)
    date = models.DateField(default=date.today,blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING,blank=True, null=True)
    body = MDTextField()

    objects = ArticleManager()

    class Meta:
        ordering = ('-date',)

    def __str__(self):
        return self.title

diary/views.py
import markdown
from django.shortcuts import render,get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from .models import Article,Category

def global_variable(request):
    categories = Category.objects.all()
    archives = Article.objects.archive()
    return locals()

# all articles
def index(request):
    articles = Article.objects.all().order_by('-date',)
    num = len(articles)
    
    page = request.GET.get('page')
    paginator = Paginator(articles, 10)
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)

    return render(request,
                'diary/index.html',
                locals())

def category(request,cid):
    articles = Article.objects.filter(category_id=cid).order_by('-date',)
    num = len(articles)
    category = Category.objects.get(id=cid)

    page = request.GET.get('page')
    paginator = Paginator(articles, 5)
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)
    return render(request,
            'diary/category.html',
            locals())

def show(request,sid):
    article = get_object_or_404(Article,pk=sid)
    # markdown.extensions.extra：用于标题、表格、引用这些基本转换
    # markdown.extensions.codehilite：用于语法高亮
    # markdown.extensions.toc：用于生成目录
    article.body = markdown.markdown(article.body,
            extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
                'markdown.extensions.toc',
                ])
    previous_articles = Article.objects.filter(date__lt=article.date,category=article.category)
    if previous_articles:
        previous_article = previous_articles[0]
    next_articles = Article.objects.filter(date__gt=article.date,category=article.category)
    if next_articles:
        next_article = next_articles.last()
    return render(request,
                'diary/show.html',
                locals())

def tag(request,tag):
    tag = Tag.objects.get(name=tag)
    articles = Article.objects.filter(tags__name=tag)
    num = len(articles)

    page = request.GET.get('page')
    paginator = Paginator(articles, 5)
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)
    return render(request,
            'diary/tag.html',
            locals())

def archive(request,year,month):
    archive = "%s年%s月" % (year,month)
    articles = Article.objects.filter(date__year=year,date__month=month)
    num = len(articles)

    page = request.GET.get('page')
    paginator = Paginator(articles, 5)
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)
    return render(request,
            'diary/archive.html',
            locals())
    

def search(request):
    query = request.GET.get('search')
    articles = Article.objects.filter(Q(body__contains=query) | Q(title__contains=query)) 
    num = len(articles)
    page = request.GET.get('page')
    paginator = Paginator(articles, 5)
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)
    return render(request,
            'diary/search.html',
            locals())

diary/templates/diary/about.html
{% extends "diary/base.html" %}
{% block content %}
<div id="main-container" class="container clearfix">
    <section class="post-left">
        <div class="breadcrumb">您的位置： <a itemprop="breadcrumb" href="/">首页</a> » 我是谁？</div>
        <div class="post-main clearfix">
            <h1 class="post-title">我是谁?</h1>
            <div class="post-con clearfix">
                <div class="article-meta">
                    <span class="item">2020年9月9日</span>
                </div>
                <article class="article-content">
                    <p>我是谁</p>
                </article>
            </div>
        </div>
    </section>
    <!-- /post-right -->
    <aside class="post-right hidden-xs">
        </section><!-- /联系方式 -->
        <div class="post-right-item">
            <h4 class="post-right-title">联系方式</h4>
                <p>Phone:18611896669</p>
                <p>Email:me@zhangzhixiong.com</p>
            </div>
        </div>
    </aside>
</div>
{% endblock %}

diary/templates/diary/archive.html
{% extends "diary/base.html" %}
{% load diary_tags %}
{% block content %}
<div id="main-container" class="container clearfix">
    <section class="post-left">
        <div class="breadcrumb">您的位置： <a itemprop="breadcrumb" href="{% url "diary:index" %}">首页</a> » <span
                                                                    class="current">{{ archive }}</span></div>
        <div class="index-main clearfix">
            <div class="main-title">
                <h4 class="post-left-title">{{ archive }}（共计{{ num }}篇）</h4>
            </div>
            <div class="row">
                {% for article in articles %}
                    <div class="article-box clearfix excerpt-1">
                        <div class="col-md-12">
                            <h2><a href="{% url "diary:index" %}show-{{ article.id }}.html" target="_blank"
                                                                                         title="{{ article.title }}">{{ article.title }}</a></h2>
                            <p class="txtcont hidden-xs">{{ article.excerpt }}</p>
                            <div class="meta"><span class="label label-info"><a
                                                    href="{% url "diary:index" %}list-{{ article.category.id }}.html">{{ article.category.name }}</a></span>
                                <time class="item"><i
                                      class="fa fa-clock-o"></i>{{ article.date|date:"Y月m月d日 周w"|weekchinese }}
                                </time>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="pagination">
                <ul>
                    {% if articles.has_previous %}
                        <li class="prev-page"><a href="?page={{ articles.previous_page_number }}">上一页</a></li>
                    {% endif %}

                    {% for num in paginator.page_range %}
                        {% list_page articles.number num %}
                    {% endfor %}

                    {% if articles.has_next %}
                        <li class="next-page"><a href="?page={{ articles.next_page_number }}">下一页</a></li>
                    {% else %}

                    <li class="next-page"></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </section>
    {% include "diary/right.html" %}
</div>
{% endblock %}

diary/templates/diary/base.html
<!DOCTYPE HTML>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-dns-prefetch-control" content="on" />
    <meta http-equiv="X-UA-Compatible" content="IE=11,IE=10,IE=9,IE=8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="apple-mobile-web-app-title" content="张志雄,张志雄的日记">
    <title>张志雄的日记</title>
    <link rel='stylesheet' id='bootstrap-css'  href="{% static "css/bootstrap.min.css" %}" type='text/css' media='all' />
    <link rel='stylesheet' id='fontawesome-css'  href="{% static "css/font-awesome.min.css" %}" type='text/css' media='all' />
    <link rel='stylesheet' id='stylesheet-css'  href="{% static "css/style.css" %}" type='text/css' media='all' />
    <link rel='stylesheet' id='raxus-css'  href="{% static "css/raxus.css" %}" type='text/css' media='all' />
    <link rel='stylesheet' id='open-social-style-css'  href="{% static "css/os.css" %}"type='text/css' media='all' />
</head>

<body class="home blog site-layout-2">
<!-- 头部 -->
<header class="fix-wrap" id="fix-wrap">
<div class="fix-main clearfix pr" id="fix-main" _hover-ignore="1"> <a href="{% url 'diary:index' %}" class="index-logo">
    <img src="static/picture/black-logo.png" alt="张志雄日记"></a>
<nav class="nav fl">
    <ul id="fix-list" class="fix-list clearfix">
    <li id="menu-item-24086" class="menu-item"><a href="{% url 'diary:index' %}">首页</a></li>
    {% for category in categories %}
    <li id="menu-item-117720" class="menu-item">
        <a href="{% url 'diary:index' %}category-{{ category.id }}.html">{{ category.name }}</a></li>
    {% endfor %}
    </ul>
</nav>
    <form method="get" class="index-search  hidden-xs" action="{% url "diary:index" %}search/" >
        <input class="text" name="search" type="text" placeholder="输入关键字" value="">
        <button class="submit" type="submit"><i class="fa fa-search"></i></button>
    </form>
</div>
</header>

<!-- 中间部分 -->
{% block content %}
{% endblock %}

<!-- 底部 -->
<footer class="footer">
    <p>学习,学习,再学习.</p>
</footer>
<script src="{% static "js/bundle.js" %}"></script>
<script type="text/javascript" src="{% static "js/view-history.js" %}"></script>
<script type='text/javascript' src="{% static "js/push.js" %}" ></script>
<script type='text/javascript' src="{% static "js/jquery.min.js" %}"></script>
<script type='text/javascript' src="{% static "js/bootstrap.min.js" %}"></script>
<script type='text/javascript' src="{% static "js/raxus-slider.min.js" %}"></script>
<script type='text/javascript' src="{% static "js/loader.js" %}"></script>
<script type='text/javascript' src="{% static "js/bj-lazy-load.min.js" %}" ></script>
<script type='text/javascript' src="{% static "js/os.js" %}"></script>
</body>
</html>

diary/templates/diary/category.html
{% extends "diary/base.html" %}
{% load diary_tags %}
{% block content %}
<div id="main-container" class="container clearfix">
    <section class="post-left">
        <div class="breadcrumb">您的位置： <a itemprop="breadcrumb" href="{% url "diary:index" %}">首页</a> » <span
                                                                    class="current">{{ category.name }}</span></div>
        <div class="index-main clearfix">
            <div class="main-title">
                <h4 class="post-left-title">分类：{{ category.name }}(共计{{ num }}篇)</h4>
            </div>
            <div class="row">
                {% for article in articles %}
                    <div class="article-box clearfix excerpt-1">
                        <div class="col-md-12">
                            <h2><a href="{% url "diary:index" %}show-{{ article.id }}.html" target="_blank"
                                                                                         title="{{ article.title }}">{{ article.title }}</a></h2>
                            <p class="txtcont hidden-xs"><a href="{% url "diary:index" %}show-{{ article.id }}.html"
                                                            target="_blank"
                                                            title="{{ article.title }}">{{ article.excerpt }}</a></p>
                            <div class="meta"><span class="label label-info"><a
                                                    href="{% url "diary:index" %}list-{{ category.id }}.html">{{ category.name }}</a></span>
                                <time class="item"><i
                                      class="fa fa-clock-o"></i>{{ article.date|date:"Y月m月d日 周w"|weekchinese }}
                                </time>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="pagination">
                <ul>
                    {% if articles.has_previous %}
                        <li class="prev-page"><a href="?page={{ articles.previous_page_number }}">上一页</a></li>
                    {% endif %}

                    {% for num in paginator.page_range %}
                        {% list_page articles.number num %}
                    {% endfor %}

                    {% if articles.has_next %}
                        <li class="next-page"><a href="?page={{ articles.next_page_number }}">下一页</a></li>
                    {% else %}

                    <li class="next-page"></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </section>
    {% include "diary/right.html" %}
</div>
{% endblock %}

diary/templates/diary/index.html
{% extends "diary/base.html" %}
{% load diary_tags %}
{% block content %}
<body class="home blog site-layout-2">
    <div id="main-container" class="container clearfix">
        <section class="post-left">
            <!-- /最新日志 -->
            <div class="index-main clearfix">
                <div class="main-title">
                    <h4 class="post-left-title fl">所有日志（共计{{ num }}篇）</h4>
                    <div class="fr"></div>
                </div>
                <div class="row">
                    {% for article in articles %} 
                        <div class="article-box clearfix excerpt-1">
                            <div class="col-md-12">
                                <h2><a href="{% url "diary:index" %}show-{{ article.id }}.html" target="_blank" title="{{ article.title }}">{{ article.title }}</a></h2>
                                <p class="txtcont hidden-xs"><a href="{% url 'diary:index' %}show-{{ article.id }}.html" target="_blank"
                                                   title="{{ article.excerpt }}">{{ article.excerpt }}</a></p>
                                <div class="meta"><span class="label label-info"><a
                                                        href="{% url "diary:index" %}category-{{ article.category.id }}.html">{{ article.category }}</a></span>
                                    <time class="item"><i class="fa fa-clock-o"></i>{{ article.date|date:"Y年m月d日 周w"|weekchinese }}
                                    </time>
                                </div>
                            </div>
                        </div>
                    {% endfor %} 
                </div>
            <div class="pagination">
                <ul>
                    {% if articles.has_previous %}
                        <li class="prev-page"><a href="?page={{ articles.previous_page_number }}">上一页</a></li>
                    {% endif %}

                    {% for num in paginator.page_range %}
                        {% list_page articles.number num %}
                    {% endfor %}

                    {% if articles.has_next %}
                        <li class="next-page"><a href="?page={{ articles.next_page_number }}">下一页</a></li>
                    {% else %}

                    <li class="next-page"></li>
                    {% endif %}
                </ul>
            </div>
        </section>
        {% include "diary/right.html" %}
    </div>
{% endblock %}

diary/templates/diary/page.html
<!DOCTYPE HTML>
<html>
<head>
<meta charset="UTF-8">
<meta http-equiv="x-dns-prefetch-control" content="on" />
<meta http-equiv="X-UA-Compatible" content="IE=11,IE=10,IE=9,IE=8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
<meta name="apple-mobile-web-app-title" content="PythonTOP,拓普Python学院">
<title>拓普Python学院,Python!</title>

<link rel='stylesheet' id='bootstrap-css'  href='static/css/bootstrap.min.css' type='text/css' media='all' />
<link rel='stylesheet' id='fontawesome-css'  href='static/css/font-awesome.min.css' type='text/css' media='all' />
<link rel='stylesheet' id='stylesheet-css'  href='static/css/style.css' type='text/css' media='all' />
<link rel='stylesheet' id='raxus-css'  href='static/css/raxus.css' type='text/css' media='all' />
<link rel='stylesheet' id='open-social-style-css'  href='static/css/os.css'type='text/css' media='all' />
<meta name='robots' content='index,follow' />
<meta name="keywords" content="互联网,产品经理,产品设计,用户体验,交互设计,网站运营,移动互联网">
<meta name="description" content="聚焦互联网前沿资讯，网络精华内容，交流产品心得。 每天为你速递最新、最鲜、最有料的互联网科技资讯！">
</head>

<body class="home blog site-layout-2">

<!-- 头部 -->
<header class="fix-wrap" id="fix-wrap">
<div class="fix-main clearfix pr" id="fix-main" _hover-ignore="1"> <a href="/" class="index-logo">
    <img src="static/picture/black-logo.png" alt="拓普Python学院,Python!"></a>
<nav class="nav fl">
    <ul id="fix-list" class="fix-list clearfix">

<li id="menu-item-24086" class="menu-item"><a href="/">首页</a></li>

<li id="menu-item-117720" class="menu-item">
 <a href="/list-1.html">Django</a></li>

<li id="menu-item-117720" class="menu-item">
 <a href="/list-2.html">Python</a></li>

<li id="menu-item-117720" class="menu-item">
 <a href="/list-3.html">Linux</a></li>

<li id="menu-item-117720" class="menu-item">
 <a href="/list-4.html">Mysql</a></li>

<li id="menu-item-117720" class="menu-item">
 <a href="/list-5.html">运维知识</a></li>

<li id="menu-item-117720" class="menu-item">
 <a href="/list-6.html">我的日记</a></li>

<li id="menu-item-24086" class="menu-item"><a href="/about/">关于博主</a></li>


</ul>
</nav>
    <form method="get" class="index-search  hidden-xs" action="/s/" >
        <input class="text" name="search" type="text" placeholder="输入关键字" value="">
        <button class="submit" type="submit"><i class="fa fa-search"></i></button>
    </form>
</div>
</header>

 <div id="main-container" class="container clearfix">
	<section class="post-left">
		<div class="breadcrumb">您的位置： <a itemprop="breadcrumb" href="/">首页</a> » <span class="current">关于我们</span></div>				<div class="post-main clearfix">
			<h1 class="post-title">关于我们</h1>
			<div class="post-con clearfix">
				<div class="article-meta"> <span class="item">2018-10-09</span></div>
				<article class="article-content">
					<p>1、本网站属于个人的非赢利性网站，转载的文章遵循原作者的版权声明，如果原文没有版权声明，按照目前互联网开放的原则，我们将在不通知作者的情况下，转载文章;如果原文明确注明“禁止转载”，我们一定不会转载。如果我们转载的文章不符合作者的版权声明或者作者不想让我们转载您的文章的话，请来信告知.</p>
<p>2、本网站转载文章仅为传播更多信息之目的，凡在本网站出现的信息，均仅供参考。本网站将尽力确保所提供信息的准确性及可靠性，但不保证信息的正确性和完整性，且不对因信息的不正确或遗漏导致的任何损失或损害承担责任。</p>
<p>3、任何透过本网站网页而链接及得到的资讯、产品及服务，本网站概不负责，亦不负任何法律责任。</p>
<p>4、本网站所刊发、转载的文章，其版权均归原作者所有，如其他媒体、网站或个人从本网下载使用，请在转载有关文章时务必尊重该文章的著作权，保留本网注明的“稿件来源”，并自负版权等法律责任。</p>


				</article>

			</div>

		</div>
				<!-- /文章 -->
	</section>
	<!-- /post-left -->
	<!-- /post-right -->
<aside class="post-right hidden-xs">
<!-- /关注我们 -->
            <div class="post-right-item">
                <h4 class="post-right-title">关注我们</h4>
                <div class="wid-about">
                    <p>拓普Python学院，欢迎关注！</p>
                    <img src="static/picture/weixinqr.jpg" width="160" height="160">
                </div>
                <div class="wid-about">
                    <p><strong>联系方式:</strong></p>
                    <p>QQ:445813</p>
                    <p>Email：445813@qq.com</p>
                </div>
            </div>

</aside>
</div>
<!-- /主体 -->
<!-- 底部 -->


<!-- 底部 -->
<footer class="footer">
<div class="copyright"> © 2010- 2018 · All Rights Reserved
    · <a href="https://www.django.cn">Django中文网</a>
    · <a href="http://www.miibeian.gov.cn" target="_blank">湘ICP备17023990号</a> 版权所有 © Django中文网</div>
</footer>
<script src="static/js/bundle.js"></script>
<script type="text/javascript" src="static/js/view-history.js"></script>
<script type='text/javascript' src="static/js/push.js" ></script>
<script type='text/javascript' src='static/js/jquery.min.js'></script>
<script type='text/javascript' src='static/js/bootstrap.min.js'></script>
<script type='text/javascript' src='static/js/raxus-slider.min.js'></script>
<script type='text/javascript' src='static/js/loader.js'></script>
<script type='text/javascript' src='static/js/bj-lazy-load.min.js' ></script>
<script type='text/javascript' src='static/js/os.js'></script>

</body>
</html>

diary/templates/diary/right.html
{% load diary_tags %}
<!-- /post-right -->
<aside class="post-right hidden-xs">
    <div class="p-4 post-right-item">
        <h4 class="post-right-title">文章归档</h4>
        {% for archive in archives %}
            <ol class="list-unstyled mb-0">
                <li><a href="{% url 'diary:index' %}archive/{{ archive | slice:":4" }}/{{ archive | slice:"5:7" }}">{{ archive }}</a></li>
            </ol>
        {% endfor %}
    </div>
    <div class="post-right-item">
        <h4 class="post-right-title">联系方式</h4>
            <p>Phone:18611896669</p>
            <p>Email:me@zhangzhixiong.com</p>
        </div>
    </div>
</aside>

diary/templates/diary/search.html
{% extends "diary/base.html" %}
{% load diary_tags %}
{% block content %}
<div id="main-container" class="container clearfix">
    <section class="post-left">
        <div class="breadcrumb">您的位置： <a itemprop="breadcrumb" href="{% url "diary:index" %}">首页</a> » <span
                                                                    class="current">关键词：{{ query }}</span></div>
        <div class="index-main clearfix">
            <div class="main-title">
                <h4 class="post-left-title">关键词：{{ query }}（共计{{ num }}篇）</h4>
            </div>
            <div class="row">
                {% for article in articles %}
                    <div class="article-box clearfix excerpt-1">
                        <div class="col-md-12">
                            <h2><a href="{% url "diary:index" %}show-{{ article.id }}.html" target="_blank"
                                                                                         title="{{ article.title }}">{{ article.title }}</a></h2>
                            <p class="txtcont hidden-xs"><a href="{% url "diary:index" %}show-{{ article.id }}.html"
                                                            target="_blank"
                                                            title="{{ article.title }}">{{ article.excerpt }}</a></p>
                            <div class="meta"><span class="label label-info"><a
                                                    href="{% url "diary:index" %}list-{{ categoryofarticle.id }}.html">{{ categoryofarticle.name }}</a></span>
                                <time class="item"><i
                                      class="fa fa-clock-o"></i>{{ article.date|date:"Y月m月d日 周w"|weekchinese }}
                                </time>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="pagination">
                <ul>
                    {% if articles.has_previous %}
                    <li class="prev-page"><a href="{% url 'diary:index' %}s?search={{ query }}&page={{ articles.previous_page_number }}">上一页</a></li>
                    {% endif %}

                    {% for num in paginator.page_range %}
                        {% search_page query articles.number num %}
                    {% endfor %}

                    {% if articles.has_next %}
                    <li class="next-page"><a href="{% url 'diary:index' %}s?search={{ query }}&page={{ articles.next_page_number }}">下一页</a></li>
                    {% else %}

                    <li class="next-page"></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </section>
    {% include "diary/right.html" %}
</div>
{% endblock %}

diary/templates/diary/show.html
{% extends "diary/base.html" %}
{% load diary_tags %}
{% block content %}
<div id="main-container" class="container clearfix">
    <section class="post-left">
        <div class="breadcrumb">您的位置： <a itemprop="breadcrumb" href="/">首页</a> » <a
            href="{% url "diary:index" %}list-{{ article.category.id }}.html">{{ article.category.name }}</a> »
            <span class="current">正文</div>
        <div class="post-main clearfix">
            <h1 class="post-title">{{ article.title }}</h1>
            <div class="post-con clearfix">
                <div class="article-meta">
                    <span class="item">分类：<a href="{% url "diary:index" %}list-{{ article.category.id }}.html" rel="category tag">{{ article.category.name }}</a></span>
                    <span class="item">{{ article.date|date:"Y月m月d日 周w"|weekchinese }}</span>

                </div>
                <article class="article-content">
                    {{ article.body|safe }}
                </article>
                <div class="post-tag"><span class="fa fa-tags" aria-hidden="true"></span>标签：
                    {% for tag in article.tags.all %}
                        <a href="{% url "diary:index" %}tag/{{ tag }}" rel="tag">{{ tag }}</a>
                    {% endfor %}
                </div>
                <div>
                    <div><b>上一篇：</b>
                        {% if previous_article %}
                            <a href="show-{{ previous_article.id }}.html" class="article-tag">{{ previous_article.title }}</a>
                        {% else %}
                            没有了
                        {% endif %}
                    </div>
                    <div><b>下一篇：</b>
                        {% if next_article %}
                            <a href="show-{{ next_article.id }}.html" class="article-tag">{{ next_article.title }}</a>
                        {% else %}
                            没有了
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% include "diary/right.html" %}
</div>
{% endblock %}